# Generated by Django 2.1.1 on 2018-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toca_schedule', '0002_schedule_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled',
            field=models.CharField(max_length=50),
        ),
    ]
